version: "3.7"
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-linkapp}
    networks:
      - backend

  backend-service:
    build: 
      context: ./backend
    container_name: backend-service
    command: sh -c "./wait-for.sh db:5432 -- uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 3000"
    volumes:
      - ./backend:/app/  
    ports:
      - 3000:3000
    environment:
      - DATABASE_URI:${DATABASE_URI:-postgresql://user:password@db/linkapp}
    depends_on: 
      - db
    networks:
      - frontend
      - backend
  frontend-service:
      build: 
        context: ./frontend
      container_name: frontend-service
      ports:
        - 8080:80
      networks:
        - frontend
        - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  postgres_data: